<Project>
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="SonarAnalyzer.CSharp" PrivateAssets="All" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"/>
	
	</ItemGroup>
</Project>