using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using EODomain.Common;
using EODomain.Contracts;
using EODomain.Models.Account;
using EODomain.Models.WinAuth;
using EOInfrastructure.Utility;
using EODomain.Models.Admin;
using Asp.Versioning;

namespace EOWebMicroservice.Controllers.v1
{
    /// <summary>
    /// Controller to host APIs for Administrative works
    /// </summary>
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    [Authorize(Policy = "AdminAccess")]
    public class AdminController : ControllerBase
    {
        private readonly IAdminServices _adminServices;
        private readonly JwtSettings _jwtSettings;

        /// <summary>
        /// Constructor for AdminController class
        /// </summary>
        /// <param name="adminServices"></param>
        /// <param name="jwtSettings"></param>
        public AdminController(IAdminServices adminServices, IOptions<JwtSettings> jwtSettings)
        {
            _adminServices = adminServices;
            _jwtSettings = jwtSettings.Value;
        }

        /// <summary>
        /// To decrypt JWT generated by authenticate api
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost("getPlainToken")]
        [ProducesResponseType(typeof(Response<object>), StatusCodes.Status200OK)]
        public IActionResult GetPlainToken([FromBody] Token model)
        {
            CryptographyHelper crypt = new CryptographyHelper(_jwtSettings);
            return Ok(new Response<object>(crypt.AesGcmDecrypt(model.value!)));
        }



        /// <summary>
        /// To fetch user activity data within a session
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_user_activity_data_by_session_id")]
        public async Task<IActionResult> GetUserActivityDataBySessionID([FromBody] GetUserActivityDataBySessionIDRequest request)
        {
            var GetUserActivityDataBySessionresult = await _adminServices.GetUserActivityDataBySessionIDAsync(request.sessionId!, request.pageNumber, request.pageSize);
            if (GetUserActivityDataBySessionresult.employeeId== null)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                var responseData = GetUserActivityDataBySessionresult;
                int? pageCount = GetUserActivityDataBySessionresult.pageCount;
             return Ok(new PaginatedResponse<object>(responseData, request.pageNumber, request.pageSize, pageCount));
            }
        }


        /// <summary>
        /// To modify status, assigned to for an error
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("modify_error_status_by_error_id")]
        public async Task<IActionResult> ModifyErrorStatusByErrorID([FromBody] ModifyErrorStatusByErrorIDRequest request)
        {
            int errorID;
            if (int.TryParse(request.errorID, out errorID))
            {
                errorID = int.Parse(request.errorID);
            }
            else
            {
                return BadRequest(new Response<Array>(ResponseConstants.CUSTOMERROR, $"Invalid errorID type", ResponseConstants.EMPTYDATA));
            }
            string status = request.status!;
            string assignedTo = request.assignedTo!;
            var validStatus = await _adminServices.GetValidErrorStatusList();

            if (!validStatus.Exists(item => item.Equals(status, StringComparison.CurrentCultureIgnoreCase)))
            {
                return BadRequest(new Response<Array>(ResponseConstants.CUSTOMERROR, $"Invalid status type '{request.status}' Allowed fields: {validStatus[0]}, {validStatus[1]}, {validStatus[2]}", ResponseConstants.EMPTYDATA));
            }
            var ModifyErrorStatusresult = await _adminServices.ModifyErrorStatusByErrorID(errorID, status, assignedTo);
            return Ok(new Response<object>(ModifyErrorStatusresult));
        }


        /// <summary>
        /// To fetch dashboard activity data, multiple filters can be added
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_user_activity_data")]
        public async Task<IActionResult> GetUserActivityDataWithDynamicSearch([FromBody] GetLoggingDataWithDynamicSearchRequest request)
        {
            int pageNumber = request.pageNumber;
            int pageSize = request.pageSize;
            string keyword = request.keyword!;

            var GetUserActivityDataWithresult = await _adminServices.GetActivityTrackerLogsAsync(pageNumber, pageSize, keyword!);
            if (GetUserActivityDataWithresult == null || GetUserActivityDataWithresult.data == null)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                var responseData = GetUserActivityDataWithresult.data;
                int? pageCount = GetUserActivityDataWithresult.pageCount;
                return Ok(new PaginatedResponse<object>(responseData, pageNumber, pageSize, pageCount));
            }
        }


        /// <summary>
        /// To fetch the log of APIs being called from dashboard, multiple filters can be added
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_api_request_log_data")]
        public async Task<IActionResult> GetApiRequestLogDataWithDynamicSearch([FromBody] GetLoggingDataWithDynamicSearchRequest request)
        {
            int pageNumber = request.pageNumber;
            int pageSize = request.pageSize;
            string keyword = request.keyword!;

            var GetApiRequestLogDataresult = await _adminServices.GetApiRequestLogsAsync(pageNumber, pageSize, keyword!);
            if (GetApiRequestLogDataresult == null || GetApiRequestLogDataresult.data == null)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                var responseData = GetApiRequestLogDataresult.data;
                int? pageCount = GetApiRequestLogDataresult.pageCount;
                return Ok(new PaginatedResponse<object>(responseData, pageNumber, pageSize, pageCount));
            }
        }


        /// <summary>
        /// To fetch the logs of SQL queries/stored procedures used in the solution.
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_query_tracker_data")]

        public async Task<IActionResult> GetQueryTrackerDataWithDynamicSearch([FromBody] GetLoggingDataWithDynamicSearchRequest request)
        {
            int pageNumber = request.pageNumber;
            int pageSize = request.pageSize;
            string keyword = request.keyword!;

            var GetQueryTrackerDataresult = await _adminServices.GetQueryTrackerLogsAsync(pageNumber, pageSize, keyword!);
            if (GetQueryTrackerDataresult == null || GetQueryTrackerDataresult.data == null)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                var responseData = GetQueryTrackerDataresult.data;
                int? pageCount = GetQueryTrackerDataresult.pageCount;
                return Ok(new PaginatedResponse<object>(responseData, pageNumber, pageSize, pageCount));
            }
        }


        /// <summary>
        /// To fetch performance of components in dashboard, their rendering time. 
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_performance_log_data")]

        public async Task<IActionResult> GetPerformanceLogDataWithDynamicSearch([FromBody] GetLoggingDataWithDynamicSearchRequest request)
        {
            int pageNumber = request.pageNumber;
            int pageSize = request.pageSize;
            string keyword = request.keyword!;

            var GetPerformanceLogDataresult = await _adminServices.GetPerformanceLogsAsync(pageNumber, pageSize, keyword!);
            if (GetPerformanceLogDataresult == null || GetPerformanceLogDataresult.data == null)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                var responseData = GetPerformanceLogDataresult.data;
                int? pageCount = GetPerformanceLogDataresult.pageCount;
                return Ok(new PaginatedResponse<object>(responseData, pageNumber, pageSize, pageCount));
            }
        }


        /// <summary>
        /// To fetch login logs
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_login_activity_data")]

        public async Task<IActionResult> GetLoginActivityDataWithDynamicSearch([FromBody] GetLoggingDataWithDynamicSearchRequest request)
        {
            int pageNumber = request.pageNumber;
            int pageSize = request.pageSize;
            string keyword = request.keyword!;

            var GetLoginActivityDataresult = await _adminServices.GetLoginLogsAsync(pageNumber, pageSize, keyword!);
            if (GetLoginActivityDataresult == null || GetLoginActivityDataresult.data == null)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                var responseData = GetLoginActivityDataresult.data;
                int? pageCount = GetLoginActivityDataresult.pageCount;
                return Ok(new PaginatedResponse<object>(responseData, pageNumber, pageSize, pageCount));
            }
        }


        /// <summary>
        /// To fetch the error logs
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_error_logging_data")]

        public async Task<IActionResult> GetErrorLoggingDataWithDynamicSearch([FromBody] GetLoggingDataWithDynamicSearchRequest request)
        {
            int pageNumber = request.pageNumber;
            int pageSize = request.pageSize;
            string keyword = request.keyword!;
            var GetErrorLoggingDataresult = await _adminServices.GetErrorLogsAsync(pageNumber, pageSize, keyword);
            if (GetErrorLoggingDataresult == null || GetErrorLoggingDataresult.data == null)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                var responseData = GetErrorLoggingDataresult.data;
                int? pageCount = GetErrorLoggingDataresult.pageCount;
                return Ok(new PaginatedResponse<object>(responseData, pageNumber, pageSize, pageCount));
            }
        }

        
        /// <summary>
        /// To fetch users statitics related to dashboard
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_users_statistics_count")]
        public async Task<IActionResult> GetUserStatistics([FromBody] GetUserStatisticsRequest request)
        {
            var result = await _adminServices.GetUserStatisticsAsync(request);
            if (result == null)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                return Ok(new Response<object>(result));
            }
        }


        /// <summary>
        /// To fetch user screen time logs
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_users_statistics_logs")]
        public async Task<IActionResult> GetUserStatisticsLogs([FromBody] GetUserStatisticsLogsRequest request)
        {
            var result = await _adminServices.GetUserStatisticsLogsAsync(request);
            if (result == null || result.data!.Count == 0)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                return Ok(new PaginatedResponse<object>(result.data, request.pageNumber, request.pageSize, result.pageCount));
            }
        }


        /// <summary>
        /// To fetch user access logs by employee details
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_user_analytics_logs")]
        public async Task<IActionResult> GetUserAnalyticsLogs([FromBody] GetUserAnalyticsLogsRequest request)
        {
            var result = await _adminServices.GetUserAnalyticsLogsAsync(request);
            if (result == null || result.data!.Count == 0)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                return Ok(new PaginatedResponse<object>(result.data, request.pageNumber, request.pageSize, result.pageCount));
            }
        }


        /// <summary>
        /// To get user statistics to plot graph on screen
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_user_statistics_graph_data")]
        public async Task<IActionResult> GetUserStatisticsGraphData([FromBody] GetUserStatisticsGraphDataRequest request)
        {
            var result = await _adminServices.GetUserStatisticsGraphDataAsync(request);
            if (result == null || result.timeWiseData!.Count == 0 && result.distinctUsersData!.Count == 0)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                return Ok(new Response<object>(result));
            }
        }


        /// <summary>
        /// To get screen wise user statistics data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_user_analytics_screenwise")]
        public async Task<IActionResult> GetUserAnalyticsScreenWise([FromBody] GetUserAnalyticsScreenWiseRequest request)
        {
            var result = await _adminServices.GetUserAnalyticsScreenWiseAsync(request);
            if (result == null || result.screenWiseAccess!.Count == 0 && result.dayWiseScreenAccess!.Count == 0)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                return Ok(new Response<object>(result));
            }
        }


        /// <summary>
        /// To get statistics of online users
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("get_user_statistics_online_users")]
        public async Task<IActionResult> GetUserStatisticsOnlineUsers([FromBody] GetUserStatisticsOnlineUsersRequest request)
        {
            var result = await _adminServices.GetUserStatisticsOnlineUsersAsync(request);
            if (result == null || result.Count == 0)
            {
                return Ok(new Response<Array>(ResponseConstants.EMPTYOK, ResponseConstants.EMPTYOK_MESSAGE, ResponseConstants.EMPTYDATA));
            }
            else
            {
                return Ok(new Response<object>(result));
            }
        }
    }
}
