"""
BoilerCalcPipeline — generic boiler calculation pipeline.

Pattern matches the furnace_ranking pipeline exactly:

    fetch sensors  →  impute  →  evaluate calc_blueprint  →  emit long-form rows

Generic across plants. Plant-specific differences live entirely in the four
input files generated by `energy_kev.pipeline_integration.pipeline_generator`:

    local_trigger/inputs/system_config.json
    local_trigger/inputs/pipeline_input_configs.xlsx
    local_trigger/inputs/pipeline_manifest.json
    pipelines/boiler_calc/calc_blueprint.json

Output channels declared in pipeline_manifest.json:
    - output_attribute_values  : long-form (timestamp × boiler × attribute) rows
    - imputation_history       : audit trail of imputed sensor readings
"""
from __future__ import annotations

import json
import sys
import numpy as np
import pandas as pd
from pathlib import Path

_PIPELINE_DIR = Path(__file__).parent
_PROJECT_ROOT = _PIPELINE_DIR.parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from core import formula_engine, inputs
from core.system_config import tree_to_flat
from pipeline_sdk.protocol import PipelineOutput
from pipeline_sdk.run_context import RunContext


def _load_bundled(filename: str) -> dict:
    with open(_PIPELINE_DIR / filename) as f:
        return json.load(f)


def _boilers_from(system_config: dict) -> list[str]:
    return [str(x) for x in system_config["hierarchy"]["Boiler"]["identifiers"]]


# Boiler-level attributes that get emitted to output_attribute_values.
# Must match the allowed_combinations in pipeline_manifest.json.
_BOILER_LEVEL_ATTRS = [
    "STATUS", "HPS_GEN", "FUEL_FLOW", "BOILER_LOAD",
    "SPEC_EN_CONS", "SPEC_EN_CONS_OPT", "SPEC_EN_CONS_DEV",
    "FD_FAN_STEAM", "FD_FAN_STEAM_REG", "STACK_TEMP_CLIPPED",
    "FUEL_INPUT_GJ_H", "USEFUL_HEAT_GJ_H", "EFFICIENCY_PCT", "CO2_T_PER_H",
]


class BoilerCalcPipeline:
    MODEL_ID     = "boiler_calc_v1"
    VERSION      = "v1"
    PIPELINE_DIR = _PIPELINE_DIR

    def __init__(self):
        self.calc_blueprint = _load_bundled("calc_blueprint.json")

    def run(
        self,
        ctx: RunContext,
        channels: dict | None = None,
        verbose: bool = False,
    ) -> PipelineOutput:
        if verbose:
            print(f"[boiler_calc] Preparing inputs")
            print(f"    plant={ctx.plant_id}  {ctx.start_time} to {ctx.end_time} @ {ctx.interval}")

        # ── Standard pipeline input block — do not modify ────────────────────
        system_config = tree_to_flat(ctx.system_config)
        input_config  = inputs.merge_input_config(
            ctx.input_config["instantiated_attrs"],
            ctx.input_config["sensors_mapping"],
            system_config,
        )
        input_df, imputation_history = inputs.prepare(input_config, ctx)
        boilers = _boilers_from(system_config)

        if verbose:
            print(f"    input shape={input_df.shape}")
            print(f"[boiler_calc] Evaluating calc blueprint ({len(self.calc_blueprint['attributes'])} attrs × {len(boilers)} boilers)")

        # ── Run the generic calc_blueprint formulas ──────────────────────────
        calc_values = formula_engine.evaluate(input_df, self.calc_blueprint, system_config)

        if verbose:
            print(f"    calc shape={calc_values.shape}")

        # ── Emit long-form rows ──────────────────────────────────────────────
        boiler_ids = system_config["hierarchy"]["Boiler"]["id_map"]
        attr_rows  = _output_attribute_rows(
            calc_values, boilers, boiler_ids, self.MODEL_ID, ctx.run_id
        )

        if verbose:
            print(f"    {len(attr_rows)} output_attribute_values rows")

        return PipelineOutput(
            run_id=ctx.run_id,
            outputs={
                "output_attribute_values": attr_rows,
                "imputation_history":      _imputation_rows(imputation_history, ctx),
            },
        )


# ── Output helpers ────────────────────────────────────────────────────────────

def _output_attribute_rows(
    calc_values: pd.DataFrame,
    boilers: list[str],
    boiler_ids: dict[str, str],
    model_id: str,
    run_id: str,
) -> list[dict]:
    rows = []
    for ts in calc_values.index:
        ts_str = ts.isoformat()
        for b in boilers:
            element_code = boiler_ids.get(b, b)
            for attr in _BOILER_LEVEL_ATTRS:
                col = f"{b}_{attr}"
                raw = calc_values.at[ts, col] if col in calc_values.columns else np.nan
                rows.append({
                    "model_id":     model_id,
                    "run_id":       run_id,
                    "timestamp":    ts_str,
                    "element_code": element_code,
                    "attribute":    attr,
                    "value":        _safe_float(raw),
                })
    return rows


def _imputation_rows(history_df: pd.DataFrame, ctx: RunContext) -> list[dict]:
    if history_df.empty:
        return []
    return [
        {
            "model_id":       ctx.model_id,
            "run_id":         ctx.run_id,
            "timestamp":      row["timestamp"].isoformat(),
            "sensor":         row["sensor"],
            "raw_value":      row["raw_value"],
            "modified_value": row["modified_value"],
            "sip_policy":     row["sip_policy"],
        }
        for _, row in history_df.iterrows()
    ]


def _safe_float(val) -> float | None:
    try:
        v = float(val)
        return None if np.isnan(v) else v
    except (TypeError, ValueError):
        return None
