import React from 'react'
import { render, fireEvent, act, waitFor } from '@testing-library/react'
import CardContainer from './SortingModal'
import * as FavoriteService from 'services/FavoriteService'
// import { useTracking } from 'react-tracking';
import { describe, it, test, expect, vi } from 'vitest' // Assuming this is imported correctly

// vi.mock('react-tracking', () => ({
//     useTracking: () => ({
//         trackEvent: vi.fn(),
//     }),
// }));

vi.mock('config/scss/_variables.scss', () => {
  return {
    primary_white: '#ff0000',
    primary_gray: '#ff0000',
    primary_gray_2: '#ff0000',
    primary_orange: '#ff0000',
    primary_yellow: '#ff0000',
    primary_blue: '#ff0000',
  }
})

const props = {
  data: [
    {
      kpiType: 'performance',
      kpiSortID: 1,
      library: 'kpi_2_number',
      tagName: 'PMA_from_CMA_tpd',
      tagName2: null,
      displayName: 'METHANOL PRODUCTION',
      displayUom: 'MT/ DAY',
      displayDescription:
        'INDICATES THE DAILY METHANOL PRODUCTION VALUE. THE TARGET PRODUCTION IS 2500 TPD.',
      displayFormula: '[Outlet_CMA_flow_from_V_4403]*0.84*((100-17.5)/100)*24',
      value1: '2584',
      value2: '2603',
      value3: null,
      value4: null,
      valueDecimal: 0,
      category: 'process',
      state: 1,
      state2: null,
      kpiDescription:
        'DISPLAYS THE DAILY METHANOL PRODUCTION. THE TARGET PRODUCTION IS 2500 TPD.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      odsData: [
        {
          odsID: 4445,
          caseID: 6,
          requestID: null,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 44614,
          odsCauseTagName: 'EOR_ods_cause',
          causeMessage: 'Plant is near EOR',
          category: 'PRODUCTION',
          effactCauseTagName: 'methanol_production_tpd_ods_effect',
          effectMessage: 'Low Methanol production',
          causeValueActual: 95.9393535732628,
          causeValueOptimum: 96.22563791903949,
          causeUom: '%',
          suggestion:
            'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
          gap: 0.2862843457766786,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: null,
          lastOccurencetime: null,
          deviationStatus: null,
          stageID: null,
          stageName: null,
          actionUrl: null,
          businessKpiTagName: 'PMA_from_CMA_tpd',
        },
      ],
      id: 1,
    },
    {
      kpiType: 'performance',
      kpiSortID: 2,
      library: 'kpi_2_number',
      tagName: 'methanol_selectivity_from_pma',
      tagName2: null,
      displayName: 'SELECTIVITY',
      displayUom: '%',
      displayDescription:
        'INDICATES THE AMOUNT OF METHANOL PRODUCED FROM CO & CO2 CONVERTED IN THE SYNTHESIS REACTOR. HIGHER THE SELECTIVITY, BETTER IS THE PERFORMANCE.',
      displayFormula:
        '[(MOLAR FLOW OF METHANOL PRODUCED/(MOLAR FLOW OF CO, CO2 AND H2 IN MAKE UP GAS*CARBON YIELD))*100]',
      value1: '78.24',
      value2: '79.09',
      value3: null,
      value4: null,
      valueDecimal: 2,
      category: 'process',
      state: 1,
      state2: null,
      kpiDescription:
        'INDICATES METHANOL PRODUCTION WITH RESPECT TO THE AMOUNT OF CO AND CO{SUB(2)} CONVERTED IN SYNTHESIS CONVERTOR. HIGHER IS BETTER.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      odsData: [
        {
          odsID: 9472,
          caseID: 6,
          requestID: null,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 99964,
          odsCauseTagName: 'EOR_2_ods_cause',
          causeMessage: 'Plant is near EOR',
          category: 'PRODUCTION',
          effactCauseTagName: 'methanol_selectivity_from_pma_ods_effect',
          effectMessage: 'Low Selectivity in Convertor',
          causeValueActual: 78.2411509903433,
          causeValueOptimum: 79.09246181459694,
          causeUom: '%',
          suggestion:
            'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
          gap: 0.8513108242536447,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: null,
          lastOccurencetime: null,
          deviationStatus: null,
          stageID: null,
          stageName: null,
          actionUrl: null,
          businessKpiTagName: 'methanol_selectivity_from_pma',
        },
        {
          odsID: 2843,
          caseID: 6,
          requestID: 2062,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 41288,
          odsCauseTagName: 'co2_injection_1_ods_cause',
          causeMessage: 'Low CO2 injection',
          category: 'PRODUCTION',
          effactCauseTagName: 'methanol_selectivity_from_pma_ods_effect',
          effectMessage: 'Low Selectivity in Convertor',
          causeValueActual: 69.98444005722979,
          causeValueOptimum: 72.1020688777262,
          causeUom: 'MT/ DAY',
          suggestion:
            'Methanol selectivity is low at high loop pressure and drum pressure. Consider increasing CO2 injection to further improve methanol production.',
          gap: 2.1176288204964067,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: '2024-01-30T06:00:00',
          lastOccurencetime: '2024-01-30T08:00:00',
          deviationStatus: 'New',
          stageID: 0,
          stageName: 'New Alert Assignment',
          actionUrl: null,
          businessKpiTagName: 'methanol_selectivity_from_pma',
        },
      ],
      id: 2,
    },
    {
      kpiType: 'performance',
      kpiSortID: 3,
      library: 'kpi_2_number',
      tagName: 'Recycle_Ratio',
      tagName2: null,
      displayName: 'RECYCLE RATIO',
      displayUom: '%',
      displayDescription:
        'INDICATES THE RATIO OF RECYCLE SYN TO THE INLET MAKE UP GAS. LOWER THE RECYCLE BETTER IS THE PERFORMANCE.',
      displayFormula: '[RECYCLE SYN GAS FLOW/MAKE UP GAS FLOW]',
      value1: '3.02',
      value2: '3.01',
      value3: null,
      value4: null,
      valueDecimal: 2,
      category: 'process,energy,environment',
      state: 1,
      state2: null,
      kpiDescription:
        'INDICATES THE RATIO OF RECYCLE SYN GAS TO THE INLET MAKE UP GAS. LOWER IS BETTER.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      odsData: [
        {
          odsID: 2847,
          caseID: 6,
          requestID: 544,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 41285,
          odsCauseTagName: 'Reycle_ratio_ods_cause',
          causeMessage: 'High Recycle Ratio at high loop pressure',
          category: 'PRODUCTION, ENERGY, ENVIRONMENT',
          effactCauseTagName: 'Recycle_ratio_ods_effect',
          effectMessage: 'High Recycle from Convertor',
          causeValueActual: 3.0201624043503177,
          causeValueOptimum: 3.012273721978869,
          causeUom: '-',
          suggestion:
            'Recycle ratio is high at high loop pressure. Consider reducing recycle ratio to its optimum value.',
          gap: 0.007888682371448574,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: '2023-06-20T18:00:00',
          lastOccurencetime: '2024-01-30T08:00:00',
          deviationStatus: 'New',
          stageID: 0,
          stageName: 'New Alert Assignment',
          actionUrl: null,
          businessKpiTagName: 'Recycle_Ratio',
        },
      ],
      id: 3,
    },
    {
      kpiType: 'performance',
      kpiSortID: 4,
      library: 'kpi_2_number',
      tagName: 'NG_intensity_in_MMBTU_T',
      tagName2: null,
      displayName: 'ENERGY SPECIFIC CONSUMPTION',
      displayUom: 'MMBTU/ MT',
      displayDescription:
        'ENERGY SPECIFIC CONSUMPTION INDICATES THE NATURAL GAS INTENSITY, THAT IS THE TOTAL ENERGY CONSUMED (IN MMBTU) BY NATURAL GAS TO PRODUCE ONE TON OF METHANOL. LOWER THE CONSUMPTION, BETTER IS THE PERFORMANCE.',
      displayFormula:
        '[NATURAL GAS ENERGY IN FEED + NATURAL GAS ENERGY IN FUEL]/[METHANOL PRODUCTION]',
      value1: '33.36',
      value2: '33.85',
      value3: null,
      value4: null,
      valueDecimal: 2,
      category: 'energy,environment',
      state: 0,
      state2: null,
      kpiDescription:
        'INDICATES THE TOTAL ENERGY CONSUMED BY NATURAL GAS (IN MMBTU) TO PRODUCE ONE TON OF METHANOL. LOWER IS BETTER. THRESHOLD OF 2% WITH RESPECT TO BENCHMARK IS ACCEPTABLE.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      id: 4,
    },
    {
      kpiType: 'performance',
      kpiSortID: 5,
      library: 'kpi_2_number',
      tagName: 'Carbon_Yield_From_Rg',
      tagName2: null,
      displayName: 'YIELD',
      displayUom: '%',
      displayDescription:
        'INDICATES THE AMOUNT OF METHANOL PRODUCED FROM THE CO & CO2 IN THE MAKE-UP GAS. THE CARBON YIELD THRESHOLD AT THE END OF 4TH YEAR IS 95.8%',
      displayFormula:
        '[(MOLAR FLOW OF CO,CO2 CONVERTED IN SYNTHESIS REACTOR/MOLAR FLOW OF CO,CO2 IN MAKE UP GAS)*100]',
      value1: '95.94',
      value2: '96.23',
      value3: null,
      value4: null,
      valueDecimal: 2,
      category: 'process',
      state: 1,
      state2: null,
      kpiDescription:
        'INDICATES METHANOL PRODUCTION WITH RESPECT TO THE CO AND CO{SUB(2)} IN MAKE UP GAS. CARBON YIELD VARIES FROM 96.5 TO 95.5%. HIGHER IS BETTER.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      odsData: [
        {
          odsID: 4450,
          caseID: 6,
          requestID: null,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 44614,
          odsCauseTagName: 'EOR_ods_cause',
          causeMessage: 'Plant is near EOR',
          category: 'PRODUCTION',
          effactCauseTagName: 'methanol_yield_based_on_pma_ods_effect',
          effectMessage: 'Low Yield in Convertor',
          causeValueActual: 95.9393535732628,
          causeValueOptimum: 96.22563791903949,
          causeUom: '%',
          suggestion:
            'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
          gap: 0.2862843457766786,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: null,
          lastOccurencetime: null,
          deviationStatus: null,
          stageID: null,
          stageName: null,
          actionUrl: null,
          businessKpiTagName: 'Carbon_Yield_From_Rg',
        },
      ],
      id: 5,
    },
    {
      kpiType: 'performance',
      kpiSortID: 6,
      library: 'kpi_1_number',
      tagName: 'Capacity_Utilization',
      tagName2: null,
      displayName: 'CAPACITY UTILIZATION',
      displayUom: '%',
      displayDescription:
        'CAPACITY UTILIZATION IS THE PERCENTAGE OF SYNTHESIS REQACTOR FEED LOAD WITH RESPECT TO ITS BEST ACHIEVED RATE. HIGHER CAPACITY UTILIZATION IS PREFERRED.',
      displayFormula: '(FEED FLOWRATE/BEST ACHIEVED RATE)*100',
      value1: '96.3',
      value2: null,
      value3: null,
      value4: null,
      valueDecimal: 1,
      category: 'process',
      state: null,
      state2: null,
      kpiDescription:
        'CAPACITY UTILIZATION IS THE PERCENTAGE OF CONVERTOR FEED LOAD WITH RESPECT TO ITS BEST ACHIEVED RATE. BEST ACHIEVED RATE (BAR) IS THE MAXIMUM FEED PROCESSED TO THE SYSTEM IN THE LAST 1 YEAR (BASED ON 10 DAY MOVING AVERAGE) OR THE DESIGN FEED FLOW, WHICHEVER IS HIGHER. THE BAR IS CALCULATED DYNAMICALLY BASED ON LAST 1 YEAR FROM CURRENT DATE.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      id: 6,
    },
  ],
  category: 'process',
  caseId: 6,
  actualTime: 1718319600000,
  odsData: [
    {
      odsID: 4445,
      caseID: 6,
      requestID: null,
      plant: 'ARRAZI-4',
      system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
      currentAssignee: null,
      odsCauseTagID: 44614,
      odsCauseTagName: 'EOR_ods_cause',
      causeMessage: 'Plant is near EOR',
      category: 'PRODUCTION',
      effactCauseTagName: 'methanol_production_tpd_ods_effect',
      effectMessage: 'Low Methanol production',
      causeValueActual: 95.9393535732628,
      causeValueOptimum: 96.22563791903949,
      causeUom: '%',
      suggestion:
        'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
      gap: 0.2862843457766786,
      timeStamp: '2024-06-14T02:00:00',
      timeEpoch: 1718319600000,
      dueDateEpoch: null,
      dueDate: null,
      deviationTimestamp: null,
      lastOccurencetime: null,
      deviationStatus: null,
      stageID: null,
      stageName: null,
      actionUrl: null,
    },
    {
      odsID: 4450,
      caseID: 6,
      requestID: null,
      plant: 'ARRAZI-4',
      system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
      currentAssignee: null,
      odsCauseTagID: 44614,
      odsCauseTagName: 'EOR_ods_cause',
      causeMessage: 'Plant is near EOR',
      category: 'PRODUCTION',
      effactCauseTagName: 'methanol_yield_based_on_pma_ods_effect',
      effectMessage: 'Low Yield in Convertor',
      causeValueActual: 95.9393535732628,
      causeValueOptimum: 96.22563791903949,
      causeUom: '%',
      suggestion:
        'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
      gap: 0.2862843457766786,
      timeStamp: '2024-06-14T02:00:00',
      timeEpoch: 1718319600000,
      dueDateEpoch: null,
      dueDate: null,
      deviationTimestamp: null,
      lastOccurencetime: null,
      deviationStatus: null,
      stageID: null,
      stageName: null,
      actionUrl: null,
    },
    {
      odsID: 9472,
      caseID: 6,
      requestID: null,
      plant: 'ARRAZI-4',
      system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
      currentAssignee: null,
      odsCauseTagID: 99964,
      odsCauseTagName: 'EOR_2_ods_cause',
      causeMessage: 'Plant is near EOR',
      category: 'PRODUCTION',
      effactCauseTagName: 'methanol_selectivity_from_pma_ods_effect',
      effectMessage: 'Low Selectivity in Convertor',
      causeValueActual: 78.2411509903433,
      causeValueOptimum: 79.09246181459694,
      causeUom: '%',
      suggestion:
        'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
      gap: 0.8513108242536447,
      timeStamp: '2024-06-14T02:00:00',
      timeEpoch: 1718319600000,
      dueDateEpoch: null,
      dueDate: null,
      deviationTimestamp: null,
      lastOccurencetime: null,
      deviationStatus: null,
      stageID: null,
      stageName: null,
      actionUrl: null,
    },
    {
      odsID: 2847,
      caseID: 6,
      requestID: 544,
      plant: 'ARRAZI-4',
      system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
      currentAssignee: null,
      odsCauseTagID: 41285,
      odsCauseTagName: 'Reycle_ratio_ods_cause',
      causeMessage: 'High Recycle Ratio at high loop pressure',
      category: 'PRODUCTION, ENERGY, ENVIRONMENT',
      effactCauseTagName: 'Recycle_ratio_ods_effect',
      effectMessage: 'High Recycle from Convertor',
      causeValueActual: 3.0201624043503177,
      causeValueOptimum: 3.012273721978869,
      causeUom: '-',
      suggestion:
        'Recycle ratio is high at high loop pressure. Consider reducing recycle ratio to its optimum value.',
      gap: 0.007888682371448574,
      timeStamp: '2024-06-14T02:00:00',
      timeEpoch: 1718319600000,
      dueDateEpoch: null,
      dueDate: null,
      deviationTimestamp: '2023-06-20T18:00:00',
      lastOccurencetime: '2024-01-30T08:00:00',
      deviationStatus: 'New',
      stageID: 0,
      stageName: 'New Alert Assignment',
      actionUrl: null,
    },
    {
      odsID: 6118,
      caseID: 6,
      requestID: 2061,
      plant: 'ARRAZI-4',
      system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
      currentAssignee: null,
      odsCauseTagID: 2703,
      odsCauseTagName: 'activity_ods_cause',
      causeMessage: 'Low Activity',
      category: 'PRODUCTION',
      effactCauseTagName: 'Catalyst_activity_ods_effect',
      effectMessage: 'Low Catalyst activity in Convertor',
      causeValueActual: 58.98299707122356,
      causeValueOptimum: 58.17311779928277,
      causeUom: null,
      suggestion:
        'Activity is low irrespective of high loop pressure. Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
      gap: 0.8098792719407868,
      timeStamp: '2024-06-14T02:00:00',
      timeEpoch: 1718319600000,
      dueDateEpoch: null,
      dueDate: null,
      deviationTimestamp: '2024-01-30T06:00:00',
      lastOccurencetime: '2024-01-30T08:00:00',
      deviationStatus: 'New',
      stageID: 0,
      stageName: 'New Alert Assignment',
      actionUrl: null,
    },
    {
      odsID: 2843,
      caseID: 6,
      requestID: 2062,
      plant: 'ARRAZI-4',
      system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
      currentAssignee: null,
      odsCauseTagID: 41288,
      odsCauseTagName: 'co2_injection_1_ods_cause',
      causeMessage: 'Low CO2 injection',
      category: 'PRODUCTION',
      effactCauseTagName: 'methanol_selectivity_from_pma_ods_effect',
      effectMessage: 'Low Selectivity in Convertor',
      causeValueActual: 69.98444005722979,
      causeValueOptimum: 72.1020688777262,
      causeUom: 'MT/ DAY',
      suggestion:
        'Methanol selectivity is low at high loop pressure and drum pressure. Consider increasing CO2 injection to further improve methanol production.',
      gap: 2.1176288204964067,
      timeStamp: '2024-06-14T02:00:00',
      timeEpoch: 1718319600000,
      dueDateEpoch: null,
      dueDate: null,
      deviationTimestamp: '2024-01-30T06:00:00',
      lastOccurencetime: '2024-01-30T08:00:00',
      deviationStatus: 'New',
      stageID: 0,
      stageName: 'New Alert Assignment',
      actionUrl: null,
    },
  ],
  isPerformance: true,
  setShowModal: () => undefined,
  setType: () => undefined,
  type: 'performance',
  setRefetch: () => undefined,
  originalData: [
    {
      kpiType: 'performance',
      kpiSortID: 1,
      library: 'kpi_2_number',
      tagName: 'PMA_from_CMA_tpd',
      tagName2: null,
      displayName: 'METHANOL PRODUCTION',
      displayUom: 'MT/ DAY',
      displayDescription:
        'INDICATES THE DAILY METHANOL PRODUCTION VALUE. THE TARGET PRODUCTION IS 2500 TPD.',
      displayFormula: '[Outlet_CMA_flow_from_V_4403]*0.84*((100-17.5)/100)*24',
      value1: '2584',
      value2: '2603',
      value3: null,
      value4: null,
      valueDecimal: 0,
      category: 'process',
      state: 1,
      state2: null,
      kpiDescription:
        'DISPLAYS THE DAILY METHANOL PRODUCTION. THE TARGET PRODUCTION IS 2500 TPD.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      odsData: [
        {
          odsID: 4445,
          caseID: 6,
          requestID: null,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 44614,
          odsCauseTagName: 'EOR_ods_cause',
          causeMessage: 'Plant is near EOR',
          category: 'PRODUCTION',
          effactCauseTagName: 'methanol_production_tpd_ods_effect',
          effectMessage: 'Low Methanol production',
          causeValueActual: 95.9393535732628,
          causeValueOptimum: 96.22563791903949,
          causeUom: '%',
          suggestion:
            'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
          gap: 0.2862843457766786,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: null,
          lastOccurencetime: null,
          deviationStatus: null,
          stageID: null,
          stageName: null,
          actionUrl: null,
          businessKpiTagName: 'PMA_from_CMA_tpd',
        },
      ],
      id: 1,
    },
    {
      kpiType: 'performance',
      kpiSortID: 2,
      library: 'kpi_2_number',
      tagName: 'methanol_selectivity_from_pma',
      tagName2: null,
      displayName: 'SELECTIVITY',
      displayUom: '%',
      displayDescription:
        'INDICATES THE AMOUNT OF METHANOL PRODUCED FROM CO & CO2 CONVERTED IN THE SYNTHESIS REACTOR. HIGHER THE SELECTIVITY, BETTER IS THE PERFORMANCE.',
      displayFormula:
        '[(MOLAR FLOW OF METHANOL PRODUCED/(MOLAR FLOW OF CO, CO2 AND H2 IN MAKE UP GAS*CARBON YIELD))*100]',
      value1: '78.24',
      value2: '79.09',
      value3: null,
      value4: null,
      valueDecimal: 2,
      category: 'process',
      state: 1,
      state2: null,
      kpiDescription:
        'INDICATES METHANOL PRODUCTION WITH RESPECT TO THE AMOUNT OF CO AND CO{SUB(2)} CONVERTED IN SYNTHESIS CONVERTOR. HIGHER IS BETTER.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      odsData: [
        {
          odsID: 9472,
          caseID: 6,
          requestID: null,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 99964,
          odsCauseTagName: 'EOR_2_ods_cause',
          causeMessage: 'Plant is near EOR',
          category: 'PRODUCTION',
          effactCauseTagName: 'methanol_selectivity_from_pma_ods_effect',
          effectMessage: 'Low Selectivity in Convertor',
          causeValueActual: 78.2411509903433,
          causeValueOptimum: 79.09246181459694,
          causeUom: '%',
          suggestion:
            'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
          gap: 0.8513108242536447,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: null,
          lastOccurencetime: null,
          deviationStatus: null,
          stageID: null,
          stageName: null,
          actionUrl: null,
          businessKpiTagName: 'methanol_selectivity_from_pma',
        },
        {
          odsID: 2843,
          caseID: 6,
          requestID: 2062,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 41288,
          odsCauseTagName: 'co2_injection_1_ods_cause',
          causeMessage: 'Low CO2 injection',
          category: 'PRODUCTION',
          effactCauseTagName: 'methanol_selectivity_from_pma_ods_effect',
          effectMessage: 'Low Selectivity in Convertor',
          causeValueActual: 69.98444005722979,
          causeValueOptimum: 72.1020688777262,
          causeUom: 'MT/ DAY',
          suggestion:
            'Methanol selectivity is low at high loop pressure and drum pressure. Consider increasing CO2 injection to further improve methanol production.',
          gap: 2.1176288204964067,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: '2024-01-30T06:00:00',
          lastOccurencetime: '2024-01-30T08:00:00',
          deviationStatus: 'New',
          stageID: 0,
          stageName: 'New Alert Assignment',
          actionUrl: null,
          businessKpiTagName: 'methanol_selectivity_from_pma',
        },
      ],
      id: 2,
    },
    {
      kpiType: 'performance',
      kpiSortID: 3,
      library: 'kpi_2_number',
      tagName: 'Recycle_Ratio',
      tagName2: null,
      displayName: 'RECYCLE RATIO',
      displayUom: '%',
      displayDescription:
        'INDICATES THE RATIO OF RECYCLE SYN TO THE INLET MAKE UP GAS. LOWER THE RECYCLE BETTER IS THE PERFORMANCE.',
      displayFormula: '[RECYCLE SYN GAS FLOW/MAKE UP GAS FLOW]',
      value1: '3.02',
      value2: '3.01',
      value3: null,
      value4: null,
      valueDecimal: 2,
      category: 'process,energy,environment',
      state: 1,
      state2: null,
      kpiDescription:
        'INDICATES THE RATIO OF RECYCLE SYN GAS TO THE INLET MAKE UP GAS. LOWER IS BETTER.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      odsData: [
        {
          odsID: 2847,
          caseID: 6,
          requestID: 544,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 41285,
          odsCauseTagName: 'Reycle_ratio_ods_cause',
          causeMessage: 'High Recycle Ratio at high loop pressure',
          category: 'PRODUCTION, ENERGY, ENVIRONMENT',
          effactCauseTagName: 'Recycle_ratio_ods_effect',
          effectMessage: 'High Recycle from Convertor',
          causeValueActual: 3.0201624043503177,
          causeValueOptimum: 3.012273721978869,
          causeUom: '-',
          suggestion:
            'Recycle ratio is high at high loop pressure. Consider reducing recycle ratio to its optimum value.',
          gap: 0.007888682371448574,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: '2023-06-20T18:00:00',
          lastOccurencetime: '2024-01-30T08:00:00',
          deviationStatus: 'New',
          stageID: 0,
          stageName: 'New Alert Assignment',
          actionUrl: null,
          businessKpiTagName: 'Recycle_Ratio',
        },
      ],
      id: 3,
    },
    {
      kpiType: 'performance',
      kpiSortID: 4,
      library: 'kpi_2_number',
      tagName: 'NG_intensity_in_MMBTU_T',
      tagName2: null,
      displayName: 'ENERGY SPECIFIC CONSUMPTION',
      displayUom: 'MMBTU/ MT',
      displayDescription:
        'ENERGY SPECIFIC CONSUMPTION INDICATES THE NATURAL GAS INTENSITY, THAT IS THE TOTAL ENERGY CONSUMED (IN MMBTU) BY NATURAL GAS TO PRODUCE ONE TON OF METHANOL. LOWER THE CONSUMPTION, BETTER IS THE PERFORMANCE.',
      displayFormula:
        '[NATURAL GAS ENERGY IN FEED + NATURAL GAS ENERGY IN FUEL]/[METHANOL PRODUCTION]',
      value1: '33.36',
      value2: '33.85',
      value3: null,
      value4: null,
      valueDecimal: 2,
      category: 'energy,environment',
      state: 0,
      state2: null,
      kpiDescription:
        'INDICATES THE TOTAL ENERGY CONSUMED BY NATURAL GAS (IN MMBTU) TO PRODUCE ONE TON OF METHANOL. LOWER IS BETTER. THRESHOLD OF 2% WITH RESPECT TO BENCHMARK IS ACCEPTABLE.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      id: 4,
    },
    {
      kpiType: 'performance',
      kpiSortID: 5,
      library: 'kpi_2_number',
      tagName: 'Carbon_Yield_From_Rg',
      tagName2: null,
      displayName: 'YIELD',
      displayUom: '%',
      displayDescription:
        'INDICATES THE AMOUNT OF METHANOL PRODUCED FROM THE CO & CO2 IN THE MAKE-UP GAS. THE CARBON YIELD THRESHOLD AT THE END OF 4TH YEAR IS 95.8%',
      displayFormula:
        '[(MOLAR FLOW OF CO,CO2 CONVERTED IN SYNTHESIS REACTOR/MOLAR FLOW OF CO,CO2 IN MAKE UP GAS)*100]',
      value1: '95.94',
      value2: '96.23',
      value3: null,
      value4: null,
      valueDecimal: 2,
      category: 'process',
      state: 1,
      state2: null,
      kpiDescription:
        'INDICATES METHANOL PRODUCTION WITH RESPECT TO THE CO AND CO{SUB(2)} IN MAKE UP GAS. CARBON YIELD VARIES FROM 96.5 TO 95.5%. HIGHER IS BETTER.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      odsData: [
        {
          odsID: 4450,
          caseID: 6,
          requestID: null,
          plant: 'ARRAZI-4',
          system: 'SYNTHESIS PERFORMANCE MANAGEMENT',
          currentAssignee: null,
          odsCauseTagID: 44614,
          odsCauseTagName: 'EOR_ods_cause',
          causeMessage: 'Plant is near EOR',
          category: 'PRODUCTION',
          effactCauseTagName: 'methanol_yield_based_on_pma_ods_effect',
          effectMessage: 'Low Yield in Convertor',
          causeValueActual: 95.9393535732628,
          causeValueOptimum: 96.22563791903949,
          causeUom: '%',
          suggestion:
            'Consider increasing loop/drum pressure based on the available margin after monitoring the distillation efficiency.',
          gap: 0.2862843457766786,
          timeStamp: '2024-06-14T02:00:00',
          timeEpoch: 1718319600000,
          dueDateEpoch: null,
          dueDate: null,
          deviationTimestamp: null,
          lastOccurencetime: null,
          deviationStatus: null,
          stageID: null,
          stageName: null,
          actionUrl: null,
          businessKpiTagName: 'Carbon_Yield_From_Rg',
        },
      ],
      id: 5,
    },
    {
      kpiType: 'performance',
      kpiSortID: 6,
      library: 'kpi_1_number',
      tagName: 'Capacity_Utilization',
      tagName2: null,
      displayName: 'CAPACITY UTILIZATION',
      displayUom: '%',
      displayDescription:
        'CAPACITY UTILIZATION IS THE PERCENTAGE OF SYNTHESIS REQACTOR FEED LOAD WITH RESPECT TO ITS BEST ACHIEVED RATE. HIGHER CAPACITY UTILIZATION IS PREFERRED.',
      displayFormula: '(FEED FLOWRATE/BEST ACHIEVED RATE)*100',
      value1: '96.3',
      value2: null,
      value3: null,
      value4: null,
      valueDecimal: 1,
      category: 'process',
      state: null,
      state2: null,
      kpiDescription:
        'CAPACITY UTILIZATION IS THE PERCENTAGE OF CONVERTOR FEED LOAD WITH RESPECT TO ITS BEST ACHIEVED RATE. BEST ACHIEVED RATE (BAR) IS THE MAXIMUM FEED PROCESSED TO THE SYSTEM IN THE LAST 1 YEAR (BASED ON 10 DAY MOVING AVERAGE) OR THE DESIGN FEED FLOW, WHICHEVER IS HIGHER. THE BAR IS CALCULATED DYNAMICALLY BASED ON LAST 1 YEAR FROM CURRENT DATE.',
      trendLibrary: 'timeseries',
      tagNameAlias: null,
      id: 6,
    },
  ],
}

vi.mock('services/FavoriteService', () => ({
  saveKpiOrderByKey: vi.fn(),
}))

describe('CardContainer Component', () => {
  it('renders CardContainer component correctly', () => {
    const { getByText } = render(<CardContainer {...props} />)
    expect(getByText('Drag KPI cards to Arrange')).toBeInTheDocument
    expect(getByText('Default Sorting')).toBeInTheDocument
    expect(getByText('Apply Sorting')).toBeInTheDocument
    expect(getByText('Cancel')).toBeInTheDocument
  })

  it('renders CardContainer component correctly with predicted', () => {
    const { getByText } = render(
      <CardContainer {...props} isPerformance={false} type='predicted' />,
    )
    expect(getByText('Drag KPI cards to Arrange')).toBeInTheDocument
    expect(getByText('Default Sorting')).toBeInTheDocument
    expect(getByText('Apply Sorting')).toBeInTheDocument
    expect(getByText('Cancel')).toBeInTheDocument
  })

  it('handles Default Sorting button click', () => {
    const { getByText } = render(<CardContainer {...props} />)

    getByText('Apply Sorting').click()

    act(() => {
      getByText('Default Sorting').click()
    })
  })

  it('should allow drag and drop functionality', () => {
    const { getByTestId } = render(<CardContainer {...props} />)

    const mockDataTransfer = {
      dataTransfer: {
        setData: vi.fn(),
        getData: vi.fn().mockReturnValue('1'),
      },
    }

    const draggableCard = getByTestId('card-1')
    fireEvent.dragStart(draggableCard, mockDataTransfer)

    const dropTarget = getByTestId('card-2')
    fireEvent.dragOver(dropTarget)
    fireEvent.drop(dropTarget, mockDataTransfer)

    const card1 = getByTestId('card-2')
    const card2 = getByTestId('card-1')

    expect(card1).toBeInTheDocument
    expect(card2).toBeInTheDocument
  })

  it('handles Apply Sorting button click and API call', async () => {
    FavoriteService.saveKpiOrderByKey.mockResolvedValueOnce({ statuscode: 200 })

    const { getByText } = render(<CardContainer {...props} />)

    act(() => {
      getByText('Apply Sorting').click()
    })

    await waitFor(() => {
      expect(FavoriteService.saveKpiOrderByKey).toHaveBeenCalled()
    })
  })

  it('handles Cancel button click and event tracking', () => {
    const { getByText } = render(<CardContainer {...props} />)

    fireEvent.click(getByText('Cancel'))
  })
})
